### ISSUE TITLE
`TypeError: Cannot read property 'attrPush' of undefined` when building examples

### ISSUE THREAD

**Issue by cvan** [sebald/scroll-rack#10]
```
% cd examples                                         /opt/scroll-rack (master)
% node build.js                              /opt/scroll-rack/examples (master)
/opt/scroll-rack/scroll-rack.js:163
            if (err) { throw err; }
                             ^
TypeError: Cannot read property 'attrPush' of undefined
    at Object.renderPermalink (/opt/scroll-rack/helpers/renderPermalink.js:25:16)
    at /opt/scroll-rack/node_modules/markdown-it-anchor/index.js:76:14
    at Array.forEach (native)
    at Array.<anonymous> (/opt/scroll-rack/node_modules/markdown-it-anchor/index.js:65:8)
    at Core.process (/opt/scroll-rack/node_modules/metalsmith-markdownit/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/opt/scroll-rack/node_modules/metalsmith-markdownit/node_modules/markdown-it/lib/index.js:500:13)
    at MarkdownIt.render (/opt/scroll-rack/node_modules/metalsmith-markdownit/node_modules/markdown-it/lib/index.js:520:36)
    at /opt/scroll-rack/node_modules/metalsmith-markdownit/lib/index.js:36:26
    at Array.forEach (native)
    at Ware.plugin (/opt/scroll-rack/node_modules/metalsmith-markdownit/lib/index.js:27:24)
    at Ware.<anonymous> (/opt/scroll-rack/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/opt/scroll-rack/node_modules/metalsmith/node_modules/ware/lib/index.js:85:20)
    at /opt/scroll-rack/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:121:18
    at /opt/scroll-rack/node_modules/metalsmith-register-helpers/index.js:23:7
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by sebald** [comment]
Sorry for the late response.

Can you give some more context so I can reproduce your problem.

**Comment by cvan** [comment]
I don't remember - it's been a while. Can close if this isn't reproducible anymore.
